name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or your branch of choice

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use a stable LTS version like 18

      - name: Install dependencies
        run: npm install

      - name: Lint the code
        run: npm run lint

      - name: Build the React app
        run: npm run build
        env:
          CI: false
          SKIP_PREFLIGHT_CHECK: true

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}